//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class c1demoEntities : DbContext
    {
        public c1demoEntities()
            : base("name=c1demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Composite_Data_Types_ICompositionContainer> Composite_Data_Types_ICompositionContainer { get; set; }
        public virtual DbSet<Composite_Data_Types_ICustomFunctionCallEditorMapping> Composite_Data_Types_ICustomFunctionCallEditorMapping { get; set; }
        public virtual DbSet<Composite_Data_Types_IDataItemTreeAttachmentPoint> Composite_Data_Types_IDataItemTreeAttachmentPoint { get; set; }
        public virtual DbSet<Composite_Data_Types_IFlowInformation> Composite_Data_Types_IFlowInformation { get; set; }
        public virtual DbSet<Composite_Data_Types_IFolderWhiteList_Unpublished> Composite_Data_Types_IFolderWhiteList_Unpublished { get; set; }
        public virtual DbSet<Composite_Data_Types_IGeneratedTypeWhiteList_Unpublished> Composite_Data_Types_IGeneratedTypeWhiteList_Unpublished { get; set; }
        public virtual DbSet<Composite_Data_Types_IHostnameBinding> Composite_Data_Types_IHostnameBinding { get; set; }
        public virtual DbSet<Composite_Data_Types_IInlineFunction> Composite_Data_Types_IInlineFunction { get; set; }
        public virtual DbSet<Composite_Data_Types_IInlineFunctionAssemblyReference> Composite_Data_Types_IInlineFunctionAssemblyReference { get; set; }
        public virtual DbSet<Composite_Data_Types_ILockingInformation> Composite_Data_Types_ILockingInformation { get; set; }
        public virtual DbSet<Composite_Data_Types_IMediaFileData> Composite_Data_Types_IMediaFileData { get; set; }
        public virtual DbSet<Composite_Data_Types_IMediaFolderData> Composite_Data_Types_IMediaFolderData { get; set; }
        public virtual DbSet<Composite_Data_Types_IMethodBasedFunctionInfo> Composite_Data_Types_IMethodBasedFunctionInfo { get; set; }
        public virtual DbSet<Composite_Data_Types_INamedFunctionCall> Composite_Data_Types_INamedFunctionCall { get; set; }
        public virtual DbSet<Composite_Data_Types_IPackageServerSource> Composite_Data_Types_IPackageServerSource { get; set; }
        public virtual DbSet<Composite_Data_Types_IPage_en_AU> Composite_Data_Types_IPage_en_AU { get; set; }
        public virtual DbSet<Composite_Data_Types_IPage_km_KH> Composite_Data_Types_IPage_km_KH { get; set; }
        public virtual DbSet<Composite_Data_Types_IPage_Unpublished_en_AU> Composite_Data_Types_IPage_Unpublished_en_AU { get; set; }
        public virtual DbSet<Composite_Data_Types_IPage_Unpublished_km_KH> Composite_Data_Types_IPage_Unpublished_km_KH { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageFolderDefinition> Composite_Data_Types_IPageFolderDefinition { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageMetaDataDefinition> Composite_Data_Types_IPageMetaDataDefinition { get; set; }
        public virtual DbSet<Composite_Data_Types_IPagePlaceholderContent_en_AU> Composite_Data_Types_IPagePlaceholderContent_en_AU { get; set; }
        public virtual DbSet<Composite_Data_Types_IPagePlaceholderContent_km_KH> Composite_Data_Types_IPagePlaceholderContent_km_KH { get; set; }
        public virtual DbSet<Composite_Data_Types_IPagePlaceholderContent_Unpublished_en_AU> Composite_Data_Types_IPagePlaceholderContent_Unpublished_en_AU { get; set; }
        public virtual DbSet<Composite_Data_Types_IPagePlaceholderContent_Unpublished_km_KH> Composite_Data_Types_IPagePlaceholderContent_Unpublished_km_KH { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageStructure> Composite_Data_Types_IPageStructure { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageType> Composite_Data_Types_IPageType { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypeDataFolderTypeLink> Composite_Data_Types_IPageTypeDataFolderTypeLink { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypeDefaultPageContent> Composite_Data_Types_IPageTypeDefaultPageContent { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypeMetaDataTypeLink> Composite_Data_Types_IPageTypeMetaDataTypeLink { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypePageTemplateRestriction> Composite_Data_Types_IPageTypePageTemplateRestriction { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypeParentRestriction> Composite_Data_Types_IPageTypeParentRestriction { get; set; }
        public virtual DbSet<Composite_Data_Types_IPageTypeTreeLink> Composite_Data_Types_IPageTypeTreeLink { get; set; }
        public virtual DbSet<Composite_Data_Types_IParameter> Composite_Data_Types_IParameter { get; set; }
        public virtual DbSet<Composite_Data_Types_IPublishSchedule_Unpublished> Composite_Data_Types_IPublishSchedule_Unpublished { get; set; }
        public virtual DbSet<Composite_Data_Types_ISearchEngineOptimizationKeyword_en_AU> Composite_Data_Types_ISearchEngineOptimizationKeyword_en_AU { get; set; }
        public virtual DbSet<Composite_Data_Types_ISearchEngineOptimizationKeyword_km_KH> Composite_Data_Types_ISearchEngineOptimizationKeyword_km_KH { get; set; }
        public virtual DbSet<Composite_Data_Types_ISqlConnection> Composite_Data_Types_ISqlConnection { get; set; }
        public virtual DbSet<Composite_Data_Types_ISqlFunctionInfo> Composite_Data_Types_ISqlFunctionInfo { get; set; }
        public virtual DbSet<Composite_Data_Types_ISystemActiveLocale> Composite_Data_Types_ISystemActiveLocale { get; set; }
        public virtual DbSet<Composite_Data_Types_ITaskItem> Composite_Data_Types_ITaskItem { get; set; }
        public virtual DbSet<Composite_Data_Types_IUnpublishSchedule_Unpublished> Composite_Data_Types_IUnpublishSchedule_Unpublished { get; set; }
        public virtual DbSet<Composite_Data_Types_IUrlConfiguration> Composite_Data_Types_IUrlConfiguration { get; set; }
        public virtual DbSet<Composite_Data_Types_IUser> Composite_Data_Types_IUser { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserActiveLocale> Composite_Data_Types_IUserActiveLocale { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserActivePerspective> Composite_Data_Types_IUserActivePerspective { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserConsoleInformation> Composite_Data_Types_IUserConsoleInformation { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserDeveloperSettings> Composite_Data_Types_IUserDeveloperSettings { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserFormLogin> Composite_Data_Types_IUserFormLogin { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserGroup> Composite_Data_Types_IUserGroup { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserGroupActivePerspective> Composite_Data_Types_IUserGroupActivePerspective { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserGroupPermissionDefinition> Composite_Data_Types_IUserGroupPermissionDefinition { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserGroupPermissionDefinitionPermissionType> Composite_Data_Types_IUserGroupPermissionDefinitionPermissionType { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserPasswordHistory> Composite_Data_Types_IUserPasswordHistory { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserPermissionDefinition> Composite_Data_Types_IUserPermissionDefinition { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserPermissionDefinitionPermissionType> Composite_Data_Types_IUserPermissionDefinitionPermissionType { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserSettings> Composite_Data_Types_IUserSettings { get; set; }
        public virtual DbSet<Composite_Data_Types_IUserUserGroupRelation> Composite_Data_Types_IUserUserGroupRelation { get; set; }
        public virtual DbSet<Composite_Data_Types_IVisualFunction> Composite_Data_Types_IVisualFunction { get; set; }
        public virtual DbSet<Composite_Data_Types_IXmlPageTemplate> Composite_Data_Types_IXmlPageTemplate { get; set; }
        public virtual DbSet<Composite_Data_Types_IXsltFunction> Composite_Data_Types_IXsltFunction { get; set; }
        public virtual DbSet<Composite_Plugins_WebClient_SessionStateProviders_DefaultSessionStateProvider_ISessionStateEntry_Unpublished> Composite_Plugins_WebClient_SessionStateProviders_DefaultSessionStateProvider_ISessionStateEntry_Unpublished { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IBadMailMessage> CompositeC1Contrib_Email_Data_Types_IBadMailMessage { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IEventBasic> CompositeC1Contrib_Email_Data_Types_IEventBasic { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IEventClick> CompositeC1Contrib_Email_Data_Types_IEventClick { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IEventError> CompositeC1Contrib_Email_Data_Types_IEventError { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IEventOpen> CompositeC1Contrib_Email_Data_Types_IEventOpen { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IMailTemplate> CompositeC1Contrib_Email_Data_Types_IMailTemplate { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IMailTemplateContent_en_AU> CompositeC1Contrib_Email_Data_Types_IMailTemplateContent_en_AU { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IMailTemplateContent_km_KH> CompositeC1Contrib_Email_Data_Types_IMailTemplateContent_km_KH { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_IQueuedMailMessage> CompositeC1Contrib_Email_Data_Types_IQueuedMailMessage { get; set; }
        public virtual DbSet<CompositeC1Contrib_Email_Data_Types_ISentMailMessage> CompositeC1Contrib_Email_Data_Types_ISentMailMessage { get; set; }
        public virtual DbSet<Content_ContentSpot> Content_ContentSpot { get; set; }
        public virtual DbSet<Content_ContentSpot_Unpublished> Content_ContentSpot_Unpublished { get; set; }
        public virtual DbSet<Demo_Country> Demo_Country { get; set; }
        public virtual DbSet<Demo_Country_Unpublished> Demo_Country_Unpublished { get; set; }
        public virtual DbSet<Demo_Ebook_FileUpload> Demo_Ebook_FileUpload { get; set; }
        public virtual DbSet<Demo_Page_Data> Demo_Page_Data { get; set; }
        public virtual DbSet<Demo_Page_Data_Unpublished> Demo_Page_Data_Unpublished { get; set; }
    }
}
