//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IMediaFileData
    {
        public System.Guid Id { get; set; }
        public string FolderPath { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string CultureInfo { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastWriteTime { get; set; }
    }
}
