//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IDataItemTreeAttachmentPoint
    {
        public System.Guid Id { get; set; }
        public string TreeId { get; set; }
        public string Position { get; set; }
        public string InterfaceType { get; set; }
        public string KeyValue { get; set; }
    }
}
