//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Plugins_WebClient_SessionStateProviders_DefaultSessionStateProvider_ISessionStateEntry_Unpublished
    {
        public System.Guid Id { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string SerializedValue { get; set; }
    }
}
