//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IPagePlaceholderContent_km_KH
    {
        public string PublicationStatus { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ChangedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.Guid PageId { get; set; }
        public string PlaceHolderId { get; set; }
        public string Content { get; set; }
        public string SourceCultureName { get; set; }
        public System.Guid VersionId { get; set; }
    }
}
