//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IParameter
    {
        public System.Guid OwnerId { get; set; }
        public System.Guid ParameterId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string HelpText { get; set; }
        public int Position { get; set; }
        public string TypeManagerName { get; set; }
        public string WidgetFunctionMarkup { get; set; }
        public string DefaultValueFunctionMarkup { get; set; }
        public string TestValueFunctionMarkup { get; set; }
    }
}
