//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IMethodBasedFunctionInfo
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string MethodName { get; set; }
        public string Namespace { get; set; }
        public string UserMethodName { get; set; }
    }
}
