//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositeC1Contrib_Email_Data_Types_IBadMailMessage
    {
        public string SerializedMessage { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid QueueId { get; set; }
        public string MailTemplateKey { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Subject { get; set; }
    }
}
