//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IPageMetaDataDefinition
    {
        public System.Guid Id { get; set; }
        public System.Guid DefiningItemId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public System.Guid MetaDataContainerId { get; set; }
        public System.Guid MetaDataTypeId { get; set; }
        public int StartLevel { get; set; }
        public int Levels { get; set; }
    }
}
