//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IUserSettings
    {
        public string Username { get; set; }
        public string CultureName { get; set; }
        public string C1ConsoleUiLanguage { get; set; }
        public string CurrentActiveLocaleCultureName { get; set; }
        public string ForeignLocaleCultureName { get; set; }
    }
}
