//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IFlowInformation
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string ConsoleId { get; set; }
        public string SerializedFlowToken { get; set; }
        public string SerializedEntityToken { get; set; }
        public string SerializedActionToken { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
