//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IPageType
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Available { get; set; }
        public bool PresetMenuTitle { get; set; }
        public System.Guid DefaultTemplateId { get; set; }
        public string HomepageRelation { get; set; }
        public System.Guid DefaultChildPageType { get; set; }
    }
}
