//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IVisualFunction
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Namespace { get; set; }
        public string Description { get; set; }
        public string TypeManagerName { get; set; }
        public string XhtmlTemplate { get; set; }
        public int MaximumItemsToList { get; set; }
        public string OrderbyFieldName { get; set; }
        public bool OrderbyAscending { get; set; }
    }
}
