//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositeC1Contrib_Email_Data_Types_IMailTemplateContent_en_AU
    {
        public System.Guid Id { get; set; }
        public string TemplateKey { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string SourceCultureName { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
    }
}
