//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_IHostnameBinding
    {
        public System.Guid Id { get; set; }
        public string Hostname { get; set; }
        public string Culture { get; set; }
        public System.Guid HomePageId { get; set; }
        public string PageNotFoundUrl { get; set; }
        public string Aliases { get; set; }
        public bool IncludeHomePageInUrl { get; set; }
        public bool IncludeCultureInUrl { get; set; }
        public bool EnforceHttps { get; set; }
    }
}
