//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composite_Data_Types_ITaskItem
    {
        public System.Guid Id { get; set; }
        public string TaskId { get; set; }
        public string TaskManagerType { get; set; }
        public string SerializedFlowToken { get; set; }
        public System.DateTime StartTime { get; set; }
    }
}
