//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_Page_Data_Unpublished
    {
        public System.Guid RedirectTo { get; set; }
        public string PublicationStatus { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid PageId { get; set; }
        public string FieldName { get; set; }
        public System.Guid VersionId { get; set; }
    }
}
